---
- name: Vector | Download
  ansible.builtin.get_url:
    url: "{{ vector_url }}"
    dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
    mode: "0644"
  tags:
    - vector
- name: Vector | Install
  become: true
  ansible.builtin.yum:
    name: "./vector-{{ vector_version }}-1.x86_64.rpm"
  tags:
    - vector
- name: Vector | Apply template
  become: true
  ansible.builtin.template:
    src: ./templates/vector.yml.j2
    dest: "{{ vector_config_dir }}/vector.yml"
    mode: "0644"
    validate: vector validate --no-environment --config-yaml %s
  tags:
    - vector
- name: Vector | Change systemd unit
  become: true
  ansible.builtin.template:
    src: ./templates/vector.service.j2
    dest: /usr/lib/systemd/system/vector.service
    mode: "0644"
    backup: true
  tags:
    - vector
- name: Pause for 10 seconds to create vector service
  ansible.builtin.pause:
    seconds: 10
  notify: Start Vector service
  tags:
    - vector
- name: Flush handlers to restart vector
  ansible.builtin.meta: flush_handlers
  tags:
    - vector
